src/server/game/Entities/Unit/Unit.cpp

Looks like weapon damage is treated by core as physical when damage calculations are done, even if damage actually is not physical
That means arcane weapon damage will be not increased if target is affected by an aura which increases arcane damage, but it will work if aura increases physical damage
Weapon damage should be not treated only as physical when damage calculations are done
Apply Aura: Mod Damage Taken - Flat (Arcane)
Value: 1200
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=34794
An instant weapon attack that causes 50% of weapon damage
School Arcane
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=34799
.npc add temp 17976
aggro her
.cast 34794
.cast 34799
damage: ~200
Apply Aura: Mod Damage Taken - Flat (Physical)
Value: 1000 …

Core/Spells: Weapon damage and Mod Damage Taken auras

---

sql/updates/world/3.3.5/2022_06_15_01_world.sql
src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp
src/server/scripts/EasternKingdoms/zone_stranglethorn.cpp

Allows access to Gnomeregan for Horde so long as they have a Goblin Transponder. 
https://classic.wowhead.com/item=9173/goblin-transponder

Fix Horde Gnomeregan Teleport

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Movement/Spline/MoveSplineInit.cpp

- Implements the logic of creatures having 1.666% reduced speed per 1% health below 30% health.
**Tests performed**: Tested via questing and a dungeon run.

Mob Health Speed

---

src/server/game/AI/CoreAI/PetAI.h

DoAttack is now public instead of private, for use in a TSWoW epoch-core PR

DoAttack is now public instead of private

---

src/server/game/Entities/Pet/Pet.cpp

Beasts with non-typical melee damage schools now normalize to physical damage when tamed. The Reign of Lupos ends once again.

Hunter pet damage type fix

---

src/server/game/Entities/Unit/Unit.cpp

OnHealLate now also lets you read the total amount of the heal. The regular amount did not include overhealing.

OnHealLate hook tweak

---

src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/Player/Player.cpp
src/server/game/Spells/Spell.cpp
src/server/shared/SharedDefines.h

Chance of obtaining fish from fishing and the chance of receiving a skillup when successfully catching a fish have been reverted to 1.12 chances. The speed in which you catch fish has been kept in its 3.3.5 state, and so has junk fishing loot.
Fishing from a pool of fish no longer guarantees a catch regardless of your fishing skill, as that was a change made in patch 3.3.0.
Added new TSWoW hook for checking your fishing cast, allowing you to make a fishing cast fail. Includes the liquidtype that you're attempting to fish in.
Added LiquidTypes enum
internal note: It's my belief that TrinityCore actually has a better implementation than Vmangos, so its been kept mostly intact. TC uses a system called "fishingsteps" which is the amount of times you have to catch a fish before your next …

Reverting Fishing to classic

---

src/server/game/Spells/Spell.cpp

Fixed an issue where Combo Point Spenders would refund their combo points spent when the attack was partially blocked.

Combo point spenders refunding on partial blocks fix

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Creature/CreatureData.h
src/server/game/Entities/Pet/Pet.cpp
src/server/game/Entities/Pet/Pet.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Unit/StatSystem.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp

This is essentially a breaking change and is custom tailored to Epoch so shouldn't really be PRed anywhere else but required so much to change I couldn't be bothered properly marking it as such. Womp, womp.
This PR rewrites Player, Creature and Pet health regeneration to be a hybrid between TBC and Vanilla while also fixing logic bugs and inaccuracies. As well as disabling client side features like power prediction to give a proper TBC / Vanilla style 2 second tick based health and mana regen for players.
Wrath / TBC mana and health regeneration for both players and pets feels bad so we decided to port regeneration rates for those using the Vanilla spirit to HP / MP regen formula. For this to properly reflect in any other client this requires edits that we are not providing but are …

Health and Power Regeneration Rewrite

---

src/server/game/Entities/Unit/Unit.cpp

For resistance calculations, creatures and players under level 20 are now considered level 20. This fixes an issue where resistances had extreme effects at low levels, and it appears to be the blizzlike implementation according to xpoff.com Classic Era level 19 twinking sources. Further evidence to support this implementation is the in game UI, which displays your current level as 20 if you are under level 20 when you mouse over resistances.

Under level 20 resistance calculation

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/Auras/SpellAuraEffects.cpp

(cherry picked from commit fb1966fdcad4863a8cacda884030d91bdedb17b7)
Fixed an issue where Curse of Recklessness wouldn't behave properly with an active Fear or Flee effect when applied or removed.

fix HandlePreventFleeing to cancel fears

---

src/server/game/Entities/Unit/StatSystem.cpp

Fixes an issue where the Animal Handler talent was still giving pets increased Attack Power as it did during Wrath.

Animal Handler script disable

---

src/server/game/AI/CoreAI/TotemAI.h

Fixes an issue where the AttackStart function in TotemAI.cpp did nothing because the only totem it was used for (Sentry Totem) cannot attack. It now uses DamageTaken, which resolves the issue.

Sentry Totem fix

---

src/server/game/Entities/GameObject/GameObject.cpp

When a ritual object has an animation spell it should stop when the ritual is complete.
Allows us to implement custom visual feedback for assisting someone in using a Meeting Stone or with Mage/Warlock rituals.

End visual spell channel when a Ritual Object's ritual is complete.

---

src/server/game/Entities/Object/Object.cpp

cp changes from acore
-  invis obj should see eachother, credit to xinef
-  invis creatures can engage non-invis, included https://github.com/azerothcore/azerothcore-wotlk/pull/15498
**Target branch(es)**: 335/6x
**Issues addressed**: Fixes #40 
**Tests performed**: (Does it build, tested in-game, etc)
mage 80, cast invisibility outside UC
tswow 78f99d423ae9
**Known issues and TODO list**:

fix Invisibility effects do not allow you to see other invisible units

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Handlers/SpellHandler.cpp
src/server/game/Spells/Spell.h
src/server/game/Spells/SpellHistory.cpp
src/server/game/Spells/SpellHistory.h
src/server/shared/Packets/ByteBuffer.cpp
src/server/shared/Packets/ByteBuffer.h

- Implemented a system to queue and process spell or item cast requests
- Queue can store multiple casts prioritized by time requested (FIFO), allowing interactions such as using an item + casting a spell immediately after a cast finishes
- Window is set at [400ms, based on acore discussion](https://github.com/azerothcore/azerothcore-wotlk/issues/9300#issuecomment-977211452)
Uses [similar flow logic as TC master](https://github.com/TrinityCore/TrinityCore/pull/29409) and [Cata preservation](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/4430863a1e9a787a3a702b58adaf4c7bb639fa29#diff-b4a23722c5b449d326b1c0e5a75f3b51de931e42e688793fd9f1d233536a02c6R17), with some structural differences. 
One key difference is that the 335a client does not send …

implement Spell Queue System

---

src/server/game/Handlers/AuctionHouseHandler.cpp

Removed the "Auction Pending" mail you receive when an item you listed on the Auction House sells. This is something that was removed in Cataclysm because it serves no purpose and tricks people into thinking there's money in their mailbox when in reality its just a note saying you'll get your money soon. You can still view pending auctions in the Auction House interface and you receive a system message any time one of your Auctions sell, this mail was redundant.
Tested to ensure this doesn't break anything, the function disabled is rather small and only used in two places.

Removes the "Auction Pending" mail you receive when your Auctions sell but money hasn't arrived yet

---

src/server/game/Entities/Unit/Unit.cpp

The Resistance cap is now calculated based on the caster's level instead of the victim's level. This is a fix not a change, however most private servers calculate the resistance cap based on the victim's level. This fix means that the Resistance cap for players against bosses is now 315 instead of 300, making it now blizzlike. This also fixes an issue where attacking a creature or player lower level than you that had resistance would cause your spells to resist significantly more than expected.
Closes https://github.com/Project-Epoch/bugtracker/issues/8344
This PR also removes the wrath of the lich king boss resistance cap, as Wrath bosses had a special exception to the normal rule. It simply doesn't need to exist on epoch.

Resistance cap fix, now based on caster's level not victim's level

---

src/server/game/Entities/GameObject/GameObject.cpp

Fixed an issue wherein fishing skill requirements for areas were significantly higher than intended.
As a more detailed technical answer, lets look at the Bay of Storms in Azshara for example. It requires 330 fishing to be able to catch any fish there, and at 425 it becomes guaranteed that you won't catch junk. In the DB it lists 425 for that subzone. So it was accidentally requiring 425 to be able to fish there, with the guarantee being 520. This PR reduces the fetched DB value by 95 to correct this.

Fishing base skill to fish in an area fix

---

src/server/game/Entities/Unit/Unit.cpp

Fixes an issue where hunter pets used the default speed they had in Creature Template instead of the base 114% (which most NPCs have anyway).

Normalise Hunter pet speed.

---

src/server/game/Spells/Auras/SpellAuras.cpp
src/server/game/Spells/SpellEffects.cpp

This fixes the issue where the area auras do not instantly apply their effects.
Actually, they were only applying the last SPELL_EFFECT_PERSISTENT_AREA_AURA;
Flare and Frost Trap have 2 and 3 SPELL_EFFECT_PERSISTENT_AREA_AURA effects
respectively, so only the last one would be applied.
The previous fix would just cause the aura to apply briefly, and then
the aura would be unapplied until the next UPDATE_TARGET_MAP_INTERVAL.
Solves https://github.com/Project-Epoch/TrinityCore/issues/59

Allow persistent area auras to apply all of their effects upon creation.

---

src/server/game/Entities/Player/Player.cpp

Honorable Kill displays are now based off of the highest rank the target has obtained, rather than their current title, allowing players to choose other titles while still letting the enemy see what kind of player they just killed.
(PvP Rank being the Honorable Kill achievements on Epoch)

Honorable Kill display change, highest rank obtained rather than current title

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/Spell.h

Implement a small check so that if the swing spell (like heroic strike) fails the normal melee swing goes through.
vmangos, cmangos and AC all fundamentally do the same thing; check whether the swing spell fails. vmangos is probably the simplest/cleanest to adopt (at the cost of 1 more variable/method under Spell)
Tested with warrior heroic strike successfully; also checked extra attack procs with sword spec, they seem to still work.
Solves issues like https://github.com/Project-Epoch/bugtracker/issues/8331

Let melee swing go through if next melee swing spell fails.

---

src/server/game/Spells/Spell.cpp

This should solve hunter traps failing when the hunter is under any form of CC.
As it stands in TrinityCore at the moment, m_originalCaster seems to point to the Player both for the hunter casts and the trap casts, such that the trap's spell cast will be checked for the hunter's caster auras. Changing this might require up cleaning up code in a lot of other places, so we just do an *actually proper* check for a unit caster and we bail if the caster is a game object (i.e. a trap).
Solves issues like https://github.com/Project-Epoch/bugtracker/issues/2823

Bypass CheckCasterAuras if the caster is not a unit.

---

src/server/game/AI/CoreAI/PetAI.cpp
src/server/game/AI/CoreAI/UnitAI.h

Solve an issue where non-caster pets had long range abilities (like wind serpent Lightning Breath) and their AI would break since they would be ordered to MoveChase up to their max range instead of melee.
Note: GetPetChaseDistance is rather obsolete now, since we only access it for caster pets, and epoch-core has the distance hardcoded to 20y for them.
PR Notes: The check done is similar to VMangos, on vanilla the only caster pet is Imp (entry 416). They also hardcode the chase distance for caster pet to 25 yards.
I moved the canMelee variable from being calculated every PetAI::Update tick to a member under UnitAI; you can restrict its scope if you wish to PetAI only; On Vmangos they have this boolean variable for every creature by checking CREATURE_STATIC_FLAG_NO_MELEE and it is under …

Force non-caster pets to chase into melee.

---

src/server/game/Handlers/PetHandler.cpp

Should solve issues like autocast AI breaking if we manually cast a spell and it fails. Potential for more checks in the future depending on the spell result?
Notes: I am fairly certain that issues like https://github.com/Project-Epoch/bugtracker/issues/4537 break because of the lines in this commit. Try as I might I was not able to find out what the reason might be for setting the CommandAttack to false if we fail a spell? Played around with a few pets and it seemed to not break anything... in the future there's space for checking the result and clearing specific flags, potentially expanding this to allow forced spells etc (see AC)

Do not turn off CommandAttack if the pet fails a manually cast spell.

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp

Roll individually against all the entries in the caster's threat table and within aggro radius.
Any spell fail leads to a resist against all of entries.
Ignore players and player owned creatures in the spell roll.
Based on vmangos/cmangos-tbc... which have tidier implementations.

Allow Feign Death to roll against spell hit.

---

src/server/game/Combat/ThreatManager.cpp

This solves most of the cases where creatures would reset after killing your pet/totem/charmed unit.
Sort of similar to vMangos code in void
HostileReference::addThreat(float pMod).
If I am not mistaken, this threat will be added on combat start and on every pet attack.
Tested with hunter/mage/warlock pets, totems and charmed creatures with Engi helmet.

Add the owner of a pet or charmed unit on the threat list of a creature.

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h

First commit is from AC, and it solves the issue of attackers still attacking invalid targets after an MC ends (e.g. players attacking another player after an MC from a boss ends).
All credit belongs to the original author UltraNix.
Link to original commit is https://github.com/azerothcore/azerothcore-wotlk/commit/13993a0b5b45430ea7bc4868283494f0362f2a1e
The second commit is a small fix to clear combat on CHARM (and vehicles I guess, but no good way to test) type charms, solving issues like enslave demon and the hunter taming quests keeping the players in combat.
The only issue I could foresee is the threat table getting cleared for the creature/player getting charmed, getting a free threat reset out of it --> might warrant a future fix if needed.
Tested with a variety of combos between …

Add some charm fixes.

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/SpellEffects.cpp

First commit solves an issue where players auto attack after using the goblin rocket helmet, making it useless. 
Based on UltraNix's commit here https://github.com/azerothcore/azerothcore-wotlk/commit/e3ed2e99e67cf23baf67e132abf57432d9de4cc9
Second one adds a knockdown to the caster, taken from vmangos.

Fix Goblin Rocket Helm.

---

src/common/Utilities/EventProcessor.h
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuras.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/Spell.h
src/server/game/Spells/SpellEffects.cpp

Core rogue mechanic --> if you vanish while a projectile is flying towards you, it causes said projectile to evade. (also works with invisibility)
Also, adds a small epoch-specific fix where the vanish buff would remain when you removed stealth aura.
The spells defined in Unit can later on be used for other effects (e.g. clean up code in Feign Death effect).
Does not work with channeled spells whose projectiles have already left the caster's hands.
It does not address the fact that contested guards should be able to see through stealth (AFAIK).
Based on vmangos code.

Fix various vanish interactions.

---

src/server/game/Spells/SpellEffects.cpp

Modify Spell:EffectPersistentAA to handle flare effects on spell launch, and ignore them on spell effect hit, keeping the behaviour for all other spells the same.
This solves the issue where flare is not applied immediately upon casting.
I say it's a hack because we manually check for flare inside this effect application. It might be the case that we can actually call this on Spell launch for all of the Persistent AA effects, but I did not want to mess with everything else.

HACK: Handle Flare Effects on Spell Launch rather than Spell Hit.

---

src/server/game/Entities/Unit/Unit.cpp

Fixed an issue where physical pet spells, such as Claw, would benefit from the Spell Power on a pet obtained from the hunter's Ranged Attack Power.
https://github.com/Project-Epoch/bugtracker/issues/8431

Prevent pet spell power from increasing physical damage abilities

---

src/server/game/Entities/Object/Object.cpp
src/server/game/Spells/Spell.cpp

1. Stop hunter traps from starting combat when they are procced by other players (creatures still start combat).
Verified via immolation trap on classic.
based on https://github.com/vmangos/core/commit/176847a7376687f1620e1876330b57f446354dd8
2. Gameobjects stealth calculation was bugged, using twice the level of the trap (which is the same level as the hunter), and not using the m_stealth value provided by the core. After the fix, rogues should be able to see traps, whereas for other classes traps are still invisible (unless they overlevel the hunter).

Various hunter trap fixes.

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/GameObject/GameObject.h
src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Object/Object.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Groups/Group.cpp
src/server/game/Handlers/LootHandler.cpp
src/server/game/Loot/Loot.cpp
src/server/game/Loot/Loot.h
src/server/game/Loot/LootItemStorage.cpp
src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp

Ultranix's commit (at https://github.com/azerothcore/azerothcore-wotlk/commit/1b7d3708a6af5289071d5e1632853a409162f932 ) solves most of the issues by actually keeping track of the participants when a dungeon/raid boss is killed (or its loot cache is created) -- Master Looter list will only show the participants, and group loot only rolls for eligible participants.
You can still abuse this, however; If you enter the dungeon after a boss was killed and it was not looted at all, you cannot loot it either. However, as soon as someone tries to loot and and then cancels looting (releases the loot), you will be able to loot (similar to how group loot works). I solve this by checking the eligible participants when setting the lootable/interactible flags for creatures/objects.
Note: Ultranix's …

Link dungeon boss loot to the players inside the dungeon.

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Unit/StatSystem.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/scripts/Spells/spell_pet.cpp

Based on vmangos commit at https://github.com/vmangos/core/commit/2646715596d24ba205b03a7f3e1cee1c4ffa4ab9
There are two AP modifiers that the client expects, a positive one and a negative one. TC was not handling them separately in some cases (in attPowerMod), which led to bugs during applications and deapplications of AP auras.
Most of the magic is inside UpdateAttackPowerAndDamage, the AP modifiers (+, - and multiplier) are kept inside m_attackPowerMods (which replace the AP m_auraFlatModifiersGroup + pct), which is being updated via AuraEffects.
Store the base AP of creatures so that we do not fetch them on every UpdateAttackAndPower.
Tested using a variety of +/- AP auras, +/- %AP auras on player/pet/creatures... and I was not able to break it.
Should solve issues like …

Rework attack power calculations to properly use positive and negative AP mods.

---

src/server/game/AI/CoreAI/PetAI.cpp
src/server/game/Spells/Spell.cpp

Remove the check in PetAI::UpdateAI since it stops us from attacking CC'd targets altogether.
Replace with a better fix by broadcasting once to pets (and guardians for QoL?) when a CC aura is applied on the target and telling them to stop attacking. -- fix taken from vmangos

Allow pets to attack targets with breakable CC if commanded.

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h

Use the player level for pets (guardians included) and charmed units in aggro range calculations.
HACK: Reduce aggro range for pets and guardians while the player is mounted. Enemies which are attacking the pet still continue to do so.
Code taken from vmangos GetAttackDistance implementation.

Modify aggro detection range for entities controlled by the player.

---

src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/GameObject/GameObject.h
src/server/game/Entities/Item/Container/Bag.cpp
src/server/game/Entities/Item/Container/Bag.h
src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Object/Object.h
src/server/game/Entities/Object/Updates/UpdateMask.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h

Cherry-pick the Unit Field cache system from AzerothCore
- cherry-pick https://github.com/azerothcore/azerothcore-wotlk/pull/18637
- cherry-pick health fix https://github.com/azerothcore/azerothcore-wotlk/pull/19287
Some unit fields are set differently in AzerothCore. I left how TC handles the setting of those fields. 
**Target branch(es)**: 335
**Issues addressed**: 
- Closes #48 
**Tests performed**: (Does it build, tested in-game, etc)
Built with TC 382bf770a616
Epoch 08574fef9c7c
**Known issues and TODO list**:

feat: Add caching mechanism to Unit Fields

---

src/server/game/AI/CoreAI/PetAI.cpp
src/server/game/Entities/Creature/Creature.cpp

Use the higher number between default chase distance and autocast spell range.
Do not pass a ChaseAngle at all (instead of 0 angle, 2* Pi tolerance) so that the imp will path straight towards the target.

Solve imp cast range and wonky movement.

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Auras/SpellAuras.cpp
src/server/shared/SharedDefines.h
src/server/shared/enuminfo_SharedDefines.cpp

Renamed Spell Attributes2 Health Funnel to No Target Per Second Costs, based on the TBCC attribute names leak.
Removed Health Funnel's incorrect implementation, which isn't accurate for 3.3.5 or 2.4.3 or 1.12. Health Funnel should only consume as much health as it displays on the tooltip, your pet is healed for more than the amount of damage dealt to you.
Now instead the newly renamed attribute is called during the Per Second Cost code to prevent a spell from being priced for every target affected by it. Health Funnel affects both the target and the caster, which caused it to get priced at double the intended amount.
In the case of custom content on custom servers this fixes an issue where similar effects (such as attaching a per-second cost to Drain Soul) would consume mana based on the …

Rename `SPELL_ATTR2_HEALTH_FUNNEL` to `SPELL_ATTR2_NO_TARGET_PER_SECOND_COSTS` and correct implementation of it

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h

Allow hp regen calculations to use a carry; mainly helps for hp5 potions --> a 6hp5 potion would only give 2 hp every 2 seconds, effectively being nerfed.
Based on https://github.com/vmangos/core/commit/1a9b78faf6aec131f2ef5c52dc9950439d388a6c
Fix the permanent sound/emote looping while eating and drinking
Small nitpick: We are calling RegenerateAll() whenever m_regenTimer exceeds 2000 ms, but we are not calling it with 2000 ms but with the actual m_regenTimer which has small overflow, so each tick calculation is not for a true 2000 ms tick. If the diff is small it wouldn't matter but it's just a nitpick in how the code is written

Improvements to health regen.

---

src/server/game/Entities/Unit/Unit.cpp

There is crit suppression for spells against higher level targets, however due to the int32 used it can swing the other way and players can get free spell crit against lower level targets.
From discussions on the internal discord it seems like that was an unintended interaction (and I could not find any trace of this in vmangos/cmangos), and it also slightly reduces the power level of players.
Can choose to ignore this, of course.

Do not allow spell crit suppression to underflow.

---

src/server/scripts/Spells/spell_item.cpp

Taken from vMangos implementation.
Think the SendSpellGo() was used to play the spell visual animation, unsure (and low low prio) how to do it on TC.
needs something like
INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (13006,'spell_item_gnomish_shrink_ray');
Unsure how Epoch uses databases, or if you want to do this in livescripts/datascripts; just felt like porting some easy stuff.

Implement Gnomish Shrink Ray.

---

src/server/game/Entities/Creature/Creature.cpp

https://github.com/Project-Epoch/TrinityCore/issues/45
As far as I can tell UNIT_STATE_FOCUSING is all we need set for creatures to not face the target on tick,
but I believe we should get and face the target on focus. (Notice this check is not done on ReacquireSpellFocusTarget)
This sets the UNIT_FIELD_TARGET in this case and sets the creature to face it.
I am assuming some order of operations, racecondition, or something was causing
if (!turnDisabled && noTurnDuringCast && target) SetFacingToObject(target, false)
to sometimes not work.
Currently testing this and will report findings...
Update:
The mages in deadmines were a good unit to test with, as Flamestrike is one of these no turn while casting spells.
It can be tricky to get this issue to show, as the mages will generally path a …

allow target for SPELL_ATTR5_DONT_TURN_DURING_CAST on spell focus

---

src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp

Some creatures or calls to random movement generator were passed a wander distance <= 1, which broke the random wander frand call since it overrides the minimum.  This ensures the frand call sets the max to whatever the _wander distance is and the min.

Fix wander distance crash

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/Spell.h
src/server/game/Spells/SpellEffects.cpp
src/server/scripts/Spells/spell_warlock.cpp

-Added totalTicks to the damage bonus calculator methods and divide the flat bonus by that amount.
Total ticks is determined from the AuraEffect directly or for triggered spells from the triggering aura if its periodic.
I do not have extensive knowledge of the expected wow stats and multipliers so please review and test to determine if this is the intended fix.  If some of the flat calculations are already correct damage 'per tick' then we need to partition those amounts from the amounts we need to divide by totalTicks.

Divide flat bonus by total ticks if is periodic

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp

From looking at the spell:
// Passive Used
20711- dummy(4) and increase spirit(137), if killed while have it cast spirit of redemption
// Not sure if used, but looks similar to 20711
35618- spell aura school absorb (69), spirit(137)
// Cast on Kill
Manually checks if (AuraEffect const* aurEff = victim->GetAuraEffect(SPELL_AURA_DUMMY, SPELLFAMILY_PRIEST, 0, 0, 0x200))
which is the passive given by 20711 that its active, if so casts
27827- heal, water breathing, shapeshift
// On shapeshift as a result of 27827
27792- unattackable, zero mana cost, root in place
27795- pacify, 176 (spirit of redemption aura), interrupt regen
All of the reactive auras do everything but prevent in-flight attacks.
Ways to fix:
Edit DBCs:
-Modify any of the spells that get set to include the immunities
-Add auras …

Spirit of Redemption Aura Apply (176) Remove in flight spells

---

src/server/game/Spells/Spell.cpp

In theory should resolve part of https://github.com/Project-Epoch/bugtracker/issues/2749
```
effect applies to spells with a delay, same as mage clearcasting: it isn't buffing the next spell that is already being cast as it should (spell should check for buff present when finishing cast), instead it only buffs the second spell afterwards, the spell checks for the effect being present when the cast begins instead - this leads to several procs being lost unused
```
The spell system scares me I want a review of this.

Recalc power cost right at the end of casting

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Unit/StatSystem.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Handlers/SpellHandler.cpp
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Auras/SpellAuras.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/Spell.h
src/server/game/Spells/SpellEffects.cpp
src/server/scripts/Spells/spell_pet.cpp
src/server/scripts/Spells/spell_priest.cpp
src/server/scripts/Spells/spell_warlock.cpp

Added full support for elemental and dual weapon damage types.
Removed non-physical flat bonuses for melee spells that use a magic school (Seal of Command)

Weapon Damage Types Unlock and Remove flat spell bonuses from melee calculation

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Object/Object.h
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Auras/SpellAuras.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/Spell.h

Add damage school to IsImmunedToSpell rather than invoking IsImmunedToDamage from PreprocessSpellHit

Spell Damage immunity fixes

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Auras/SpellAuras.cpp
src/server/game/Spells/SpellEffects.cpp
src/server/scripts/Spells/spell_priest.cpp
src/server/scripts/Spells/spell_warlock.cpp

Remove division by total ticks for flat mod bonuses, this is accounted for in the spell coefficient.

remove total ticks from flat mod calcs

---

src/server/game/Achievements/AchievementMgr.cpp
src/server/game/Entities/Player/Player.cpp
src/server/shared/DataStores/DBCEnums.h
src/server/shared/DataStores/DBCStructure.h

Implements new achievement criteria type called Cast Skill Spell, which gives you credit when you cast a spell that grants a skillup from the chosen skill.

Cast Skill Spell new achievement criteria

---

src/server/game/Spells/SpellInfo.cpp

Fixes an issue where Bladestorm was not immuning any effects, and it now behaves as intended.

Bladestorm hackfix for launch

---

src/server/game/Achievements/AchievementMgr.cpp

Fixed an issue where the profession craft 500 achievements counted across every profession, ignoring what skill it was intended for.

Profession craft achieves fix

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h

Performance improvements for High diffs:
We will scale back the relocation notifies in two ways:
The default notify period is 1 second.  We use a baseline diff of 300ms.  We use a max threshold of 1500ms.
We get a scale factor of 1->5 as the diff scales from 300ms->1500ms, clamped.  meaning for diffs >= 1500 we will
have a notify period of 5 seconds, ensuring we do not send every single notify on every single frame.  If the diff > 5 seconds
this cannot be avoided and will fall off a cliff.
We also use this same diff range to scale back the notify distance from 100 yards -> 50 yards.
To ensure better distribution of notifies we switch to using the guid to determine whether an object will update - this should reduce the clustering of update timers and provide a more consistent distribution.

Dynamic relocations perf

---

src/server/authserver/Main.cpp
src/server/worldserver/Main.cpp

workaround for tracy freezing the game thread on exit. likely cause is https://github.com/wolfpld/tracy/issues/589 which is unresolved on the tracy repo for now. this only resolves the issue of tracy hanging on graceful exit, it does not resolve the issue of tracy hanging on crash, but this can be handled by tswow.

tracy freeze fix
