sql/updates/world/3.3.5/2022_07_08_00_epoch_world.sql, src/server/scripts/World/npcs_special.cpp
- Add Creature Text for all relevant creatures.
- Rewrite main quest script to match Classic references.
- Quest is now actually completable.
**Target branch(es)**: 335
**Issues addressed**: Fixes #
**Tests performed**: (Does it build, tested in-game, etc)
Tested both horde and alliance success and fail.
**Known issues and TODO list**:
=> Triage Rewrite

src/server/game/Entities/GameObject/GameObject.cpp, src/server/game/Entities/GameObject/GameObject.h, src/server/game/Handlers/LootHandler.cpp
- Mining nodes can now fail attempt.
- Mining nodes can now have multiple uses if the data is in db.
=> Old School Mining

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/blackrock_spire.h, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp
Adds Solakar Flamewreath to BRS script
=> Adds Solakar Flamewreath to BRS script

src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/game/Spells/SpellEffects.cpp
Disabled damage calculation of Steady Shot so it can be livescripted.
Disabled script for Kill Command so it can be livescripted.
=> Disabled scripts for Steady Shot and Kill Command.

src/server/game/Entities/Player/Player.cpp
Adds a new hook that'll allow War Mode to function the same as if you were on a PvP Realm
=> New PvP hook for War Mode fixes

src/server/game/Instances/InstanceScript.cpp, src/server/game/Instances/TSCustomInstance.cpp, src/server/game/Instances/TSCustomInstance.h, src/server/game/Scripting/ScriptMgr.cpp
Expands the `CustomInstance` class used by TS-WoW for custom dungeons to have more features needed for handling saving / loading better.
=> Expanded Custom Instance

src/server/scripts/World/npcs_special.cpp
Training dummies now drop combat with a target after 15 seconds of not being attacked, up from 5 seconds.
Training dummies with max health higher than 1 (Heroic Training Dummy) can now be damaged down to 1 hp and now regenerate health once they leave combat with all targets.
=> Training Dummy improvements

src/server/game/Entities/Object/Object.cpp
Rework stealth detection formula to mimic Vmangos, bringing it much closer to Classic.
Fixed a bug where stealth effects could never be seen through if the stealther was behind the target, even if that target was extremely higher level than you.
Compared results with Classic to ensure accuracy, unfortunately I do not have a rogue so I was only able to test using a fresh level 1, whom I leveled to 2 as well. However I was able to replicate perfect accuracy with the limited sample size.
Vmangos code referenced from:
https://github.com/vmangos/core/blob/faf8e61b838b645803097db4a8de359dab352691/src/game/Objects/Unit.cpp#L6623
=> Rework stealth mechanic to match Vmangos/Classic

dep/recastnavigation/Detour/Include/DetourNavMeshQuery.h, src/common/Collision/Management/MMapFactory.h, src/common/Collision/Management/MMapManager.h, src/common/Nav/DetourFilters.h, src/common/Utilities/MathUtil.h, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Movement/MovementGenerators/ChaseMovementGenerator.cpp, src/server/game/Movement/MovementGenerators/ChaseMovementGenerator.h, src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp, src/server/game/Movement/MovementGenerators/FollowMovementGenerator.h, src/server/game/Movement/PathGenerator.cpp, src/server/game/Movement/PathGenerator.h, src/server/scripts/Commands/cs_mmaps.cpp
- Tidied up a variable name that triggered me.
- Display area and type in .mmap loc for debugging.
- More adjustments to detecting water.
- Added a Detour query filter to better choose paths based on slopes.
- Fire proper movement inform in Follow movement.
- Update chase generator to 400ms blizzlike tick and to use predicted positions.
- Improvements to NPC's following NPC's where they will now correctly inherit the targets speed out of combat.
=> More Movement Improvements

src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Unit/StatSystem.cpp, src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/game/Spells/Auras/SpellAuraEffects.h
Numerous underlying stat calculation changes that are used throughout the core / attack tables.
- AGI -> Crit Formula.
- AGI -> Dodge Formula.
- Dodge Percentage Formula.
- Crit Percent Formula.
- Parry Percent Formula.
- Block Percent Formula.
- Improvements to Hit calculations.
- Removed DR for numerous stats.
=> Stat Calculations and Formulas

src/server/game/Entities/Creature/CreatureData.h, src/server/game/Entities/Creature/enuminfo_CreatureData.cpp, src/server/game/Entities/Unit/Unit.cpp
Pinches an unused creature template extra flag to serve as a way to opt in to OnUpdateAI calls so it won't fire for every mob.
Serves as minor optimisation.
=> OnUpdateAI Optimisation

src/server/game/Entities/Totem/Totem.cpp
Added hook for when shaman totems despawn for any reason.
=> Totem OnDespawn TSWoW hook

src/server/game/Spells/SpellInfo.cpp
Remove hardcoded warlock curse stacking rule to implement it in the DB instead
=> Remove hardcoded warlock curse stacking rule

src/server/game/AI/CoreAI/TotemAI.h, src/server/game/Entities/Object/Object.cpp, src/server/game/Entities/Object/Object.h, src/server/game/Entities/Totem/Totem.cpp
Fix issue with Shaman Grounding Totem. Now it properly unsummon when hit by Polymorph or Fear spells (#38)
=> Fix issue with Shaman Grounding Totem. Now it properly unsummon when hit by Polymorph or Fear spells (#38)

sql/updates/auth/3.3.5/2024_10_06_00_auth.sql, sql/updates/auth/3.3.5/2024_10_08_00_auth.sql, sql/updates/world/3.3.5/2024_10_06_00_world.sql, sql/updates/world/3.3.5/2024_10_08_00_world.sql, src/server/game/Accounts/RBAC.h, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Handlers/MovementHandler.cpp, src/server/game/Maps/Map.cpp, src/server/game/Miscellaneous/Language.h, src/server/scripts/Commands/cs_list.cpp, src/server/scripts/Commands/cs_tele.cpp
Closes https://github.com/Project-Epoch/TrinityCore/issues/58
Closes https://github.com/Project-Epoch/TrinityCore/issues/57
=> Instance GM Commands

src/server/game/Spells/Spell.cpp
If there are no checks, spells like mend pet fail silently if the pet is out of range / dead / out of LoS, as if the pet "evades" the spell (but mana is still taken). This should solve most of the issues one might encounter.
Code is taken from VMangos -- apart from the LoS ignoring M2 which seems to be common throughout TC code.
To investigate: Improved Mend Pet fails LoS Check. (unaffected by this commit)
Tested on hunter spells and wotlk warlock voidwalker sacrifice.
=> Add range/alive/LoS checks for casts with implicit pet target.

src/common/Utilities/Duration.h
This hack is not present in TrinityCore nor tswow/TrinityCore and it completely breaks compilation on my system.
=> Fix build issues from chrono hack

src/server/game/Spells/Auras/SpellAuraEffects.cpp
https://github.com/Project-Epoch/TrinityCore/issues/44
ApplyForceReaction to child factions when given a parent faction
=> ApplyForceReaction to child factions

src/server/game/Entities/Creature/Creature.cpp
=> Fixes for SPELL_ATTR5_DONT_TURN_DURING_CAST

src/server/game/Maps/Map.cpp
Account for formations being modified by update
=> fix formation update crash

src/server/game/Spells/Auras/SpellAuraEffects.cpp
make sure to unapply immunity for spirit of redemption
=> make sure to unapply immunity for spirit of redemption

src/server/game/Entities/Creature/Creature.cpp, src/server/game/Entities/Creature/Creature.h
based on https://github.com/vmangos/core/commit/183203611d796a4958bbd64a394728f325257cbd
It can potentially act a bit funky if solo, if you get out of range of the creature it might stop updating and you are in combat for quite a distance (might be intended).
If there is another player nearby the creature so that it ticks regularly, there are no issues.
=> Refresh leash timer periodically while under crowd control.

src/server/scripts/EasternKingdoms/ScarletMonastery/boss_mograine_and_whitemane.cpp
-Cast Lay on Hands on Whitemane when resurrected
-Set non attackable during sleep->res period in case players get around sleep.
=> SM cath script fixes

src/server/game/Entities/Totem/Totem.cpp, src/server/game/Entities/Totem/Totem.h
Previouslybroke totems, this fixes
=> fix totems

src/server/game/Server/WorldSocket.cpp, src/server/game/World/World.cpp, src/server/game/World/World.h, src/server/worldserver/worldserver.conf.dist
Kick when hit player limit rather than queue
=> add noqueue setting

src/server/game/Entities/Creature/Creature.cpp, src/server/game/Entities/Player/Player.cpp, src/server/game/Maps/Map.cpp, src/server/game/Maps/Map.h
Make Map::GetVisibilityRange scale with diff for all references to it.
=> Dynamic map range period

src/server/game/Server/WorldSession.cpp
Skip sending most queue position updates when higher in the queue.
=> throttle queue position updates
